### ISSUE TITLE
dictionary.jsを参照する機能はありますか。

### ISSUE THREAD

**Issue by m-yazaki-line** [textlint-ja/textlint-rule-ja-no-abusage#5]
問）
dictionary.jsをnode_modulesフォルダの外に出して運用する方法はないでしょうか。

状況）
現在は、textlintからtextlint-rule-ja-no-abusageを利用しています。メッセージを出力する機能が非常に気に入りました。
自社のルールを、node_modules\textlint-rule-ja-no-abusage\src\dictionary.js を書き換えて登録しています。しかし、このファイルを書き換えても、ほかの環境で利用するときに、npm installするとtextlint-rule-ja-no-abusageのデフォルトのdictionary.jsに戻ってしまいます。

そこで解決方法の1つとして、dictionary.jsをnode_moduleフォルダの外に出して、運用する方法がないものか、と思いました。
ドキュメントには書かれていないようです。。

**Comment by yumetodo** [comment]
textlint-rule-ja-no-abusageをforkして書き換えてcommitしてどこかへpushしておき、npmでinstallするときにgitから引っ張ってくればいいかと思われます。

**Comment by azu** [comment]
[dict/prh.yml](https://github.com/textlint-ja/textlint-rule-ja-no-abusage/blob/master/dict/prh.yml) の辞書(正規表現ベース)の方は[textlint-rule-prh](https://github.com/textlint-rule/textlint-rule-prh)というルールで、辞書だけ外部管理できるようになっています。
しかし、[dictionary.js](https://github.com/textlint-ja/textlint-rule-ja-no-abusage/blob/master/src/dictionary.js)の方は、このルールを書くためにとりあえずで作った感じの仕組みであるため、[textlint-rule-prh](https://github.com/textlint-rule/textlint-rule-prh)ルールのように辞書を外部管理する仕組み(ルール)が今の所ないですね。

textlint-rule-ja-no-abusageをforkして辞書だけ変えたルールを作成するか、
辞書部分(dictionary.js)相当を外部管理できる汎用的なルールを作るかですね。

幸いロジックは[morpheme-match-all](https://github.com/azu/morpheme-match-all)でライブラリ化してあるのでどちらも難しくないですが、辞書を外部管理したいという需要があるなら汎用的なルールを作る感じのほうがいいですかね?
(なんというルール名にすればいいのかがちょっと悩みどころですが… 形態素解析のtokenベースでマッチする辞書を扱うルール という名前付けが難しい)

**Comment by m-yazaki** [comment]
ありがとうございます！

辞書部分(dictionary.js)相当を外部管理できる汎用的なルールがあると、社内で布教しやすいので嬉しいです。

チームごとに（対象読者ごとに）使うルールを変えたいと思っています。

名前は…今のままで外部に辞書を放り出せるだけでも私は十分ですが…

**Comment by azu** [comment]
@m-yazaki-line 作ってみました
[textlint-ja/textlint-rule-morpheme-match: 形態素解析結果のTokenベースの辞書でマッチするtextlintルール](https://github.com/textlint-ja/textlint-rule-morpheme-match)

意図した感じにうごきそうですかね?

**Comment by m-yazaki** [comment]
早い！ありがとうございます！

**Comment by azu** [comment]
このIssue自体は閉じても良さそうなので閉じてしまいます。
https://github.com/textlint-ja/textlint-rule-morpheme-match
の方に問題がありましたら、そちらにIssueを立ててください。
